# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrightLocal < Formula
  desc "One-command local Bright Energy Dashboard stack for non-developers"
  homepage "https://github.com/bright-eu/bright-local"
  version "0.1.13"
  license "UNLICENSED"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bright-eu/bright-local-dist/releases/download/v0.1.13/bright-local_0.1.13_darwin_amd64.tar.gz"
      sha256 "d96ed0f8806acec7bac7d95056dafbf8bf7129f2ab0c5528c430bcbaf640f276"

      define_method(:install) do
        bin.install "bright-local"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bright-eu/bright-local-dist/releases/download/v0.1.13/bright-local_0.1.13_darwin_arm64.tar.gz"
      sha256 "8b709ea5abbd2ed7848af8e87f9bfc37275d1060ce269e6487b8148e8f19c325"

      define_method(:install) do
        bin.install "bright-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bright-eu/bright-local-dist/releases/download/v0.1.13/bright-local_0.1.13_linux_amd64.tar.gz"
      sha256 "f6c0ace08a53e4ddcb0eeedb4920d0b95f17636258410739bdaea997ac1654f3"
      define_method(:install) do
        bin.install "bright-local"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bright-eu/bright-local-dist/releases/download/v0.1.13/bright-local_0.1.13_linux_arm64.tar.gz"
      sha256 "98d32514724ab94a00861e0b595010171b2750e0e7ef91b182f883b3c080b2af"
      define_method(:install) do
        bin.install "bright-local"
      end
    end
  end

  def caveats
    <<~EOS
      Before `brew uninstall bright-local`, run:

        bright-local purge

      That removes the Docker containers, volumes, and images the
      stack pulled. `brew uninstall` only removes the CLI binary.
    EOS
  end

  test do
    system "#{bin}/bright-local", "version"
  end
end
