# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrightLocal < Formula
  desc "One-command local Bright Energy Dashboard stack for non-developers"
  homepage "https://github.com/bright-eu/bright-local"
  version "0.1.1"
  license "UNLICENSED"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bright-eu/bright-local-dist/releases/download/v0.1.1/bright-local_0.1.1_darwin_amd64.tar.gz"
      sha256 "4bd4ae4cde2be291b818b31f9581281895121219b0b671969add22d662b49442"

      define_method(:install) do
        bin.install "bright-local"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bright-eu/bright-local-dist/releases/download/v0.1.1/bright-local_0.1.1_darwin_arm64.tar.gz"
      sha256 "17da48fd716a72bd817381a880d5ffed5ddb9fa15a171c3242ebca32c01bb94d"

      define_method(:install) do
        bin.install "bright-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bright-eu/bright-local-dist/releases/download/v0.1.1/bright-local_0.1.1_linux_amd64.tar.gz"
      sha256 "ce7ae204f1c0b675dd64ce9e8140e867a3fa1149ca396215256fc227c6b4a656"
      define_method(:install) do
        bin.install "bright-local"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bright-eu/bright-local-dist/releases/download/v0.1.1/bright-local_0.1.1_linux_arm64.tar.gz"
      sha256 "18b3fbc36ca5f30cfc33b3fa4f3e56289058939c2667b978cf6f7434da360a1b"
      define_method(:install) do
        bin.install "bright-local"
      end
    end
  end

  test do
    system "#{bin}/bright-local", "version"
  end
end
